version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: awesome-pizza-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:pizzadb
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SERVER_PORT=8080
    networks:
      - pizza-network
    restart: unless-stopped

networks:
  pizza-network:
    driver: bridge