spring:
  application:
    name: awesome-pizza

  datasource:
    url: jdbc:h2:mem:pizzadb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true

server:
  port: 8080

logging:
  level:
    com.awesomepizza: DEBUG
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,mappings,scheduledtasks,loggers,threaddump,heapdump
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    info:
      enabled: true
  info:
    env:
      enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
    ping:
      enabled: true
  metrics:
    enable:
      all: true
    export:
      simple:
        enabled: true

info:
  app:
    name: Awesome Pizza Order Management System
    description: Pizza ordering system for Awesome Pizza restaurant
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 21
  team:
    name: Hamid
    email: hamid@awesomepizza.com

