spring:
  application:
    name: awesome-pizza

  datasource:
    url: jdbc:h2:mem:pizzadb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true

server:
  port: 8080

logging:
  level:
    com.awesomepizza: DEBUG
    org.springframework.web: INFO