spring:
  application:
    name: awesome-pizza-docker

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:pizzadb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
        format_sql: false
    show-sql: false

  h2:
    console:
      enabled: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.awesomepizza: ${LOG_LEVEL:INFO}
    org.springframework: WARN
  file:
    name: /app/logs/awesome-pizza.log

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html